version: '3.8'

services:
  logstash-agent:
    container_name: logstash-agent
    image: logstash:7.17.5
    volumes:
      - ./logstash-agent.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - streamdal-network

  log-processor:
    build: .
    container_name: log-processor
    volumes:
      - .:/app
    environment:
     - STREAMDAL_LOG_PROCESSOR_STREAMDAL_SERVER=streamdal-server:8082
     - STREAMDAL_LOG_PROCESSOR_LISTEN_ADDR=0.0.0.0:6000
     - STREAMDAL_LOG_PROCESSOR_LOGSTASH_ADDR=logstash-server:7002
     - STREAMDAL_LOG_PROCESSOR_STREAMDAL_TOKEN=1234
    ports:
      - "6000:6000"
      - "7002:7002"
    networks:
      - streamdal-network
    depends_on:
      - logstash-agent
      - logstash-server

  logstash-server:
    container_name: logstash-server
    image: logstash:7.17.15
    volumes:
      - ./logstash-server.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9600:9600"
    networks:
      - streamdal-network
    depends_on:
      - logstash-agent

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.15
    platform: "linux/amd64"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - streamdal-network
    
  kibana:
    container_name: kibana
    image: kibana:7.17.15
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - streamdal-network
    depends_on:
      - elasticsearch

networks:
  streamdal-network:
    external: true

volumes:
  elasticsearch-data:
    driver: local
